# Generated by Django 5.2.11 on 2026-02-13 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_is_paid_order_payment_intent_id_and_more'),
        ('restaurants', '0002_restaurant_is_approved_restaurant_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique transaction ID from payment gateway', max_length=255, unique=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('cod', 'Cash on Delivery')], default='stripe', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, help_text='Payment gateway response data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(help_text='Customer who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='orders.order')),
                ('restaurant', models.ForeignKey(help_text='Restaurant for this transaction (for owner filtering)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('order_confirmed', 'Order Confirmed'), ('refund_processed', 'Refund Processed')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payment_system.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Payment Notification',
                'verbose_name_plural': 'Payment Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['-created_at'], name='payment_sys_created_bcc6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['restaurant', '-created_at'], name='payment_sys_restaur_d67ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['customer', '-created_at'], name='payment_sys_custome_9fc499_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payment_sys_status_605fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentnotification',
            index=models.Index(fields=['recipient', '-created_at'], name='payment_sys_recipie_4ddf26_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentnotification',
            index=models.Index(fields=['is_read'], name='payment_sys_is_read_dea432_idx'),
        ),
    ]
