# Generated by Django 5.2.11 on 2026-02-14 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_restaurant_latitude_restaurant_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('vegan', 'Vegan')], default='veg', max_length=20)),
                ('category', models.CharField(choices=[('cooked', 'Cooked Food'), ('raw', 'Raw Materials'), ('packaged', 'Packaged Food'), ('baked', 'Baked Goods'), ('other', 'Other')], default='cooked', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the food')),
                ('image', models.ImageField(blank=True, help_text='Image of the food item', null=True, upload_to='donation_images/')),
                ('original_quantity', models.IntegerField(help_text='Total quantity available initially')),
                ('available_quantity', models.IntegerField(help_text='Quantity still available for booking')),
                ('quantity_unit', models.CharField(choices=[('servings', 'Servings'), ('kg', 'Kilograms'), ('pieces', 'Pieces'), ('plates', 'Plates'), ('packets', 'Packets')], default='servings', max_length=20)),
                ('quantity_description', models.CharField(blank=True, help_text='e.g., 5 kg, 10 plates', max_length=100)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate weight in kilograms', max_digits=6, null=True)),
                ('serving_count', models.IntegerField(blank=True, help_text='Number of people this can serve (deprecated - use original_quantity)', null=True)),
                ('prepared_time', models.DateTimeField(blank=True, help_text='When the food was prepared', null=True)),
                ('expiry_time', models.DateTimeField(help_text='When the food expires and should be removed from listings')),
                ('best_before', models.DateTimeField(blank=True, help_text='Recommended consumption time', null=True)),
                ('location', models.CharField(help_text='Pickup location address', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map location', max_digits=9, null=True)),
                ('contact_phone', models.CharField(help_text='Contact number for pickup', max_length=15)),
                ('contact_name', models.CharField(blank=True, help_text='Contact person name', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('partially_booked', 'Partially Booked'), ('fully_booked', 'Fully Booked'), ('collected', 'Collected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_instructions', models.TextField(blank=True, help_text='Special instructions for pickup')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, help_text='If donated by a restaurant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_booked', models.IntegerField(help_text='Quantity booked from this donation')),
                ('booking_status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('collected', 'Collected'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('booker_name', models.CharField(help_text='Name of person collecting', max_length=100)),
                ('booker_phone', models.CharField(help_text='Contact number', max_length=15)),
                ('booker_email', models.EmailField(blank=True, help_text='Email for notifications', max_length=254)),
                ('preferred_collection_time', models.DateTimeField(blank=True, help_text='When booker plans to collect', null=True)),
                ('actual_collection_time', models.DateTimeField(blank=True, help_text='When actually collected', null=True)),
                ('notes', models.TextField(blank=True, help_text='Special requests or notes')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating by booker (1-5)', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback from booker')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_bookings', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='donations.donation')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donation_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='donations.donation')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'expiry_time'], name='donations_d_status_f7028f_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='donations_d_donor_i_b67ace_idx'),
        ),
        migrations.AddIndex(
            model_name='donationbooking',
            index=models.Index(fields=['donation', 'booking_status'], name='donations_d_donatio_762b35_idx'),
        ),
        migrations.AddIndex(
            model_name='donationbooking',
            index=models.Index(fields=['booked_by'], name='donations_d_booked__3dea4c_idx'),
        ),
    ]
