# Generated by Django 6.0.2 on 2026-02-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_donation_accepted_by_donationproof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("collected", "Collected"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
