# Generated by Django 6.0.2 on 2026-02-13 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_alter_donation_status"),
        ("restaurants", "0002_restaurant_is_approved_restaurant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="accepted_by",
        ),
        migrations.AddField(
            model_name="donation",
            name="food_type",
            field=models.CharField(
                choices=[("veg", "Veg"), ("non-veg", "Non-Veg")],
                default="veg",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="prepared_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="reserved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reserved_donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("collected", "Collected"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
