# Generated by Django 5.2.11 on 2026-02-13 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_notification'),
        ('restaurants', '0003_restaurant_latitude_restaurant_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='quantity',
            new_name='quantity_description',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='reserved_by',
        ),
        migrations.AddField(
            model_name='donation',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Available for pickup until', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='booked_at',
            field=models.DateTimeField(blank=True, help_text='When the donation was booked', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='booked_by',
            field=models.ForeignKey(blank=True, help_text='User who booked this donation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='collection_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled pickup time', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the food item', null=True, upload_to='donation_images/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Pickup location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Pickup location longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text='Special instructions for pickup'),
        ),
        migrations.AddField(
            model_name='donation',
            name='serving_count',
            field=models.IntegerField(blank=True, help_text='Number of people this can serve', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approximate weight in kilograms', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='prepared_time',
            field=models.DateTimeField(blank=True, help_text='When the food was prepared', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='If donated by a restaurant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('collected', 'Collected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
