# Generated by Django 5.2.11 on 2026-02-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent_current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Delivery agent current latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Delivery agent current longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='agent_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time agent location was updated', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When order was confirmed after payment', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When order was delivered to customer', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Customer delivery location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Customer delivery location longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_at',
            field=models.DateTimeField(blank=True, help_text='When agent picked up order from restaurant', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Restaurant location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Restaurant location longitude', max_digits=9, null=True),
        ),
    ]
